src/bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .vews import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/profiles/urls.py
from django.urls import path
from .views import my_profile_view

app_name = 'profiles'

urlpatterns = [
    path('myprofile/', my_profile_view, name='my-profile-view')
]

src/posts/models.py
from django.db import models

# Create your models here.

src/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify

# Create your models here.


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default='no bio ...', max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def save(self, *args, **kwargs):
        ex = False
        if self.first_name and self.last_name:
            to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug = slugify(to_slug + " " + str(get_random_code()))
                ex = Profile.objects.filter(slug=to_slug).exists()

        else:
            to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOISES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOISES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

src/profiles/forms.py
from django import forms
from .models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')

src/posts/views.py
from django.shortcuts import render

# Create your views here.

src/profiles/views.py
from django.shortcuts import render
from .models import Profile
from .forms import ProfileModelForm
# Create your views here.


def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == "POST":
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }

    return render(request, 'profiles/myprofile.html', context)

src/profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}

{% block title %}
my profile
{% endblock title %}

{% block content %}

<!-- MODAL -->
<div class="ui modal mymodal">
  <i class="close icon"></i>
  <div class="header">
    Update your profile
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="{{profile.avatar.url}}">
    </div>
    <div class="description">
      <div class="ui header">Provide some additional/newest info about you</div>
      <form action="" method="POST" class="ui form" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
    </div>
  </div>
  <div class="actions">
    <button type="submit" class="ui positive right labeled icon button">
      Update
      <i class="checkmark icon"></i>
    </button>
    </form>
  </div>
</div>




<div class="ui segment">
  {% if confirm %}
    <div class="ui green message">Your profile has been updated</div>
  {% endif %}
  <h3>my profile: {{request.user}}</h3>
  <div class="ui grid">
    <div class="row">
      <div class="six wide column">
        <img class="ui medium rounded image" src="{{profile.avatar.url}}">
        <div class="row mt-5">
          <button class="ui secondary button" id="modal-btn">Update your profile</button>
        </div>
      </div>
      <div class="'ten wide column">
        <table class="ui table">
          <tbody>
            <tr>
              <td>username</td>
              <td>{{profile.user}}</td>
            </tr>
            <tr>
              <td>first name</td>
              <td>{{profile.first_name}}</td>
            </tr>
            <tr>
              <td>last name</td>
              <td>{{profile.last_name}}</td>
            </tr>
            <tr>
              <td>bio</td>
              <td>{{profile.bio}}</td>
            </tr>
            <tr>
              <td>number of friends</td>
              <td>{{profile.get_friends_no}}</td>
            </tr>
            <tr>
              <td>number of friends</td>
              <td>
                <ul>
                  {% for friend in profile.get_friends %}
                    <li>{{friend}}</li>
                  {% endfor %}
                </ul>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css-->
    <link rel="stylesheet" type="text/css" href={% static 'style.css' %}>
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

  
    <title>bffbook - {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'main/navbar.html' %}
    <div class="ui container">
      {% block content %}
      {% endblock content %}
    </div>

    {% block scripts %}
    {% endblock scripts %}
   
   <!--Custom js ADD-->
   <script type="text/javascript" src={% static 'main.js' %}></script>

  </body>
</html>

src/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
{{hello}}
<br>
{{user}}
{% endblock content %}

{% block scripts %}
<script>
$(document).ready(function(){
    console.log('working')
})
</script>
{% endblock scripts %}

src/templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}

<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>bffbook</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Board
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                        Send Invites
                    </a>
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>
        
            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                 {{ request.user }}
            </a>

            <a href="" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>